
language: c

compiler:
  - gcc

git:
  depth: 10
  submodules: false  # we update submodules manually
 
matrix:
  include:

     # OS X
     - os: osx
       osx_image: xcode11.2
       compiler: gcc
       addons:
        homebrew:
          packages:
            - ninja
          update: true
       env:
        - NODE_VERSION="13.12.0" # node abi 79
        - DO_NPM_PUBLISH=true # only attempt 'npm publish' from one job in the matrix
       
     - os: osx
       osx_image: xcode11.2
       compiler: gcc
       addons:
        homebrew:
          packages:
            - ninja
          update: true
       env: NODE_VERSION="12.16.0" # node abi 72

     - os: osx
       osx_image: xcode11.2
       compiler: gcc
       addons:
        homebrew:
          packages:
            - ninja
          update: true
       env: NODE_VERSION="11.15.0" # node abi 67

    #  - os: osx
    #    osx_image: xcode11.2
    #    compiler: gcc
    #    addons:
    #     homebrew:
    #       packages:
    #         - ninja
    #       update: true
    #    env: NODE_VERSION="14" # node abi 83

     # Linux
    #  - os: linux
    #    dist: bionic
    #    compiler: gcc
    #    env: 
    #      - NODE_VERSION="14"
    #    addons:
    #      apt:
    #       packages:
    #         - ninja-build
     - os: linux
       dist: bionic
       compiler: gcc
       env: 
         - NODE_VERSION="13.12.0"
       addons:
         apt:
          packages:
            - ninja-build
     - os: linux
       dist: bionic
       compiler: gcc
       env: NODE_VERSION="12.16.0"
       addons:
         apt:
          packages:
            - ninja-build
     - os: linux
       dist: bionic
       compiler: gcc
       env: NODE_VERSION="11.15.0"
       addons:
         apt:
          packages:
            - ninja-build

     # Windows
    #  - os: windows
    #    compiler: gcc
    #    env: NODE_VERSION="12"
    #    install:
    #     - choco install ninja

env:
  global:
   - secure: "Lp5Ylq2MKqwgl8mtJjMpilnZiRXC7kw4dBlXaMcjFyzPxOjr25TN2E88RnFhT2mMW9Bt1OyrXz1Rn/5slHcMcxSNbvRgx5LfrbIYJgTICZFudcSERegxVXxoJqSAYqxuKyPTRWG9dlGSnMd7Lkcd6q1USY7DaNdiNOiLTNvrplFBdZjtAz/3nrG8E62xct8IF+fTytIjZ31e0HndWhxeZWRX9cwQPldLSvF/0J8em0Sv5KFvx02PsLEiXk2QZ+JbO7nxZNgWCmFEfHZVkTy3kfXC0TlXpMFv75uX0lsOyEqcBIuDR4iOQ00xOcL0isOymcY1BvQKjJUoI8K79ygVJW5diaihTd9BAHXPeOa4CjWu1XOrOWRHaes4RZo4rPie2VHh2maHQpkEyj+X5Er0q1nMh8vnc5eEqaRUdce9PHSdUBKQS9uXoRIwqu/TI37XZKLCRSEfN3euAk2bwyOtq7dKNeRye2hsNVNP8Mr9pcrZgrMP3ck2adou7IHZl5+yBRoj1uB6RbqWxuR/ge5+yYYMZWN7wIkCDfPTBEn/RR+Zdv5UdpXK2XnAv1gWD7s8Q/1r5SnfEbUfCayReLqBt046ChJGevhL6ENj5ep09sy16nSkL6NzXkl0Yj7KfcOWhArwJnKQ6/AvGHN9iAdODPGVGEasax34xFEp6soR/Ew="
   - secure: "MHQvBh5E4ElQnUIwTFLfPOp9nHKFzOwhzkFRXcX8uQidmUbX2JcR1GDuDPl/S0beb+HUBftUEwkdmb0fqS/2OxmqckzijJrhJd6x6QuYVXI740hyynzaB6EbRLMG6X1AvMQ2JYygrVEhGYbFTFRC55Ssb70+W+s0+JJLqH+s/3ySYrhpbbGEGgVZx2u7FiQrfA5Ye/4yP3ezQiMxyvCi3w9ovUDag1hPXHsmeGetN5J8AZ0TGDSBneb/8LOPUuaajLkQ2vG4n1LDudu5buePaSZo9x31ZSaVWf387ilAjquTWOSGQNiQBDJ+iCGGjiv6XXWdol6e9bHEz2ySyT1wmzA3fd+LspdHFpXc3fR9tOqxLyMurla5OUZ3uvgbEyknXoutxbwRy4oUkzXE9Kp8dUEZ+TKmaBD1nU+L06I6TscLy8mpOsElq7EK6y5ec3ZSW9iC2k25Y9b76UmWIuTD+4ppOe32AERgk7CXyymQ1zBFP15nVltJzGMlh7YdUyHgffvZWAnvPBSyEoXjBTifd+rDRHdsucBrYcagDw14NESvOvUNJK9R+fjIBw5DhOZFfWMd1oTkCnG1Lqo2VQtQDO1jfUfUq7lGxwSNTTi2ScZQ+H1dlLMEj2fQDmtZidvlOWIJhNHlwj09VRaY+pQtcmrbUdi9WZYwJzEPqYVflMg="

before_install:
- scripts/validate_tag.sh
- source ./scripts/install_node.sh ${NODE_VERSION}
- node --version
- npm --version
# get commit message
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
# put local node-pre-gyp on PATH
- export PATH=./node_modules/.bin/:$PATH
# put global node-gyp on PATH
- npm install node-gyp -g
# figure out if we should publish
- PUBLISH_BINARY=false
# if we are building a tag then publish
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
# or if we put [publish binary] in the commit message
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
- git submodule update --init --recursive
# build Ziti C-SDK
- npm run build:init
- npm run build:c-sdk
# build Ziti NodeJS-SDK
- npm install --build-from-source --clang=1
# test our module
- node tests/hello.js
# purge some stuff before publishing
- npm run build:cleanup

before_script:
# if publishing, do it
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish && sleep 10; fi;
# cleanup
- node-pre-gyp clean
- node-gyp clean

script:
# if publishing, test installing from remote
- sleep 5
- INSTALL_RESULT=0
- if [[ $PUBLISH_BINARY == true ]]; then INSTALL_RESULT=$(npm install --fallback-to-build=false > /dev/null)$? || true; fi;
# if install returned non zero (errored) then we first unpublish and then call false so travis will bail at this line
- if [[ $INSTALL_RESULT != 0 ]]; then echo "returned $INSTALL_RESULT";node-pre-gyp unpublish;false; fi
# If success then we arrive here so lets clean up
- node-pre-gyp clean

after_success:
# if success then query and display all published binaries
- node-pre-gyp info

deploy:
  provider: npm
  edge: true
  email: "curt.tudor@netfoundry.io"
  api_key:
    secure: EdgahchC9LwFR+SOhFy6zSeLNgHl0IQU0tfjfLTpHxbb/toqigwGs3WXEWxnDHUazbgIhFfIm6D4BYpevPO6qPcOBKgrcjIIgGYy0xomjyEc0aWmuhesBc37288dUvaxvj1hdGG0Rw0LG77VEi8uZ9T6Vda4Lw4avk5L35YNcyuKOltR6c28n9BbXjp8/j2R4DaIOA8UipAdM9Bum60X4FxfUH3V0prq5LyKVt9o0A6dmhKx+YIyzi+KQgI6uKUijhk6h/qazE6I9R4JRaPmByK25w3QofsSSOm+t25pGtucfHySkR4tLgVe4JXka43/E49XVT0ryZoGF6/+ownBXXsZq/per6h/oKFlA4oZ0H33/bPa4mWY2j/EP/+GAso4xdHkA5/iMtgRugiL4B7nibFEOSuggdpwTQ+b97Omk0tsx/PARCZaAO0U4JaUaVQf47DM0hZRk3CWVo9V5Ke43uk3jyYK95VTL2U6as/6lW7sf7xCUhCmckKzEH95E4fFxifczFb+g97ep+8a5tLSkSr9t75ruWK7V2BlmM6gszfcqEEEqvMNEsfum3gaDuoUyFHUp6uaKb6b7TuIXZJ9tSeyLPaGCKIhhsKbjCMROcnorrOk21madRNDZAAQ4oywZm6AP6dY1B+OKV/9VbcANnVHxmLNGFMFr+sK0zaKd1c=
  on:
    tags: true
    branch: master
    condition: $DO_NPM_PUBLISH = true
