
name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: 'Misc tags'

jobs:

  # -------------------------------------------------------------------------------
  #  Do a clean build, test, and publish
  # -------------------------------------------------------------------------------
  build:

    runs-on: ${{ matrix.config.os }}

    env:
      BUILD_NUMBER: ${{ github.run_number }}
    
    strategy:
      matrix:
        config:
          - { name: "Win", os: windows-latest, cc: "cl",    cxx: "cl" }
          - { name: "Lin", os: ubuntu-latest,  cc: "gcc",   cxx: "g++" }
          - { name: "Mac", os: macos-latest,   cc: "clang", cxx: "clang++" }
        # os:
          # - ubuntu-latest
          # - macOS-latest
          # - windows-latest
        node-version: [ 12.x, 13.x, 14.x, 15.x ]
      fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
        token: ${{ secrets.ZITI_CI_GH_TOKEN }}
    
    - name: Install Ninja (Linux)
      run: sudo apt-get install -y ninja-build
      if: matrix.config.os == 'ubuntu-latest'

    - name: Install Ninja (Mac)
      run: brew install ninja
      if: matrix.config.os == 'macOS-latest'

    - name: Install Ninja (Windows)
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install ninja
      if: matrix.config.os == 'windows-latest'

    - name: gcc version
      run: |
        gcc --version
    - name: cmake version
      run: |
        cmake --version
    - name: ninja version
      run: |
        ninja --version
    - name: node version
      run: |
        node --version
    - name: npm version
      run: |
        npm --version

    - name: Build (embedded) C-SDK Phase-I (Linux | Mac)
      run: |
        mkdir ${{ runner.workspace }}/${{ github.event.repository.name }}/deps/ziti-sdk-c/build
        cd ${{ runner.workspace }}/${{ github.event.repository.name }}/deps/ziti-sdk-c/build
        cmake -G Ninja -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} ..
      if: |
        matrix.config.os == 'ubuntu-latest' ||
        matrix.config.os == 'macOS-latest'

    - name: Build (embedded) C-SDK Phase-I (Windows)
      shell: cmd
      run: |
        mkdir ${{ runner.workspace }}\${{ github.event.repository.name }}\deps\ziti-sdk-c\build
        cd ${{ runner.workspace }}\${{ github.event.repository.name }}\deps\ziti-sdk-c\build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -G "NMake Makefiles" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=OFF ..
      if: matrix.config.os == 'windows-latest'

    - name: Build (embedded) C-SDK Phase-II (Linux | Mac)
      run: |
        cd ${{ runner.workspace }}/${{ github.event.repository.name }}/deps/ziti-sdk-c/build
        cmake --build . --target all
      if: |
        matrix.config.os == 'ubuntu-latest' ||
        matrix.config.os == 'macOS-latest'

    - name: Build (embedded) C-SDK Phase-II (Windows)
      shell: cmd
      run: |
        cd ${{ runner.workspace }}\${{ github.event.repository.name }}\deps\ziti-sdk-c\build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        nmake ziti
        powershell "(Get-Childitem mbedcrypto.lib -Recurse -ErrorAction SilentlyContinue).Fullname"
        powershell "Get-Location"
      if: matrix.config.os == 'windows-latest'

    - name: Build NodeJS-SDK
      run: |
        cd ${{ runner.workspace }}/${{ github.event.repository.name }}
        npm install --build-from-source

    - name: Hello test
      run: |
        node tests/hello.js

    - name: Cleanup
      run: |
        npm run build:cleanup


