
name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: 'Misc tags'

jobs:

  # -------------------------------------------------------------------------------
  #  Do a clean build, test, and publish
  # -------------------------------------------------------------------------------
  build:

    runs-on: ${{ matrix.os }}

    env:
      BUILD_NUMBER: ${{ github.run_number }}
    
    strategy:
      matrix:
        config:
          # - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          # - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++" }
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
        node-version: [
          # '12', 
          # '13', 
          '14'
        ]

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
        token: ${{ secrets.ZITI_CI_GH_TOKEN }}
    
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        # ninja version to download. Default: 1.10.0
        version: 1.10.0

    - name: gcc version
      run: |
        gcc --version
    - name: cmake version
      run: |
        cmake --version
    - name: ninja version
      run: |
        ninja --version
    - name: node version
      run: |
        node --version
    - name: npm version
      run: |
        npm --version

    - name: Build (embedded) C-SDK Phase-I
      run: |
        mkdir ${{ runner.workspace }}/${{ github.event.repository.name }}/deps/ziti-sdk-c/build; cd ${{ runner.workspace }}/${{ github.event.repository.name }}/deps/ziti-sdk-c/build; cmake -G Ninja -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} ..

    - name: Build (embedded) C-SDK Phase-II
      run: |
        cd ${{ runner.workspace }}/${{ github.event.repository.name }}/deps/ziti-sdk-c/build; cmake --build . --target all -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 

    # - name: Build (embedded) C-SDK Phase-I
    #   uses: ashutoshvarma/action-cmake-build@master
    #   with:
    #     build-dir: ${{ runner.workspace }}/deps/ziti-sdk-c/build
    #     cc: ${{ matrix.config.cc }}
    #     cxx: ${{ matrix.config.cxx }}
    #     configure-options: -G Ninja -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    #     build-type: Release

    # - name: Build (embedded) C-SDK Phase-II
    #   uses: ashutoshvarma/action-cmake-build@master
    #   with:
    #     build-dir: ${{ runner.workspace }}/deps/ziti-sdk-c/build
    #     cc: ${{ matrix.config.cc }}
    #     cxx: ${{ matrix.config.cxx }}
    #     configure-options: --build . --target all
    #     build-type: Release

    - name: Build NodeJS-SDK
      run: |
        npm install --build-from-source

    - name: Hello test
      run: |
        node tests/hello.js

    - name: Hello test
      run: |
        npm run build:cleanup


